// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhaQULP3q1LywqGL8lqYnQZl09jV4MP4',
    appId: '1:384145309918:web:60fa1f473a09c8e00b024f',
    messagingSenderId: '384145309918',
    projectId: 'to-do-list-616ab',
    authDomain: 'to-do-list-616ab.firebaseapp.com',
    storageBucket: 'to-do-list-616ab.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQ9EarqEXLDemYwe8PXUjaUE8GCYgdCeE',
    appId: '1:384145309918:android:ac5fed96b77510a00b024f',
    messagingSenderId: '384145309918',
    projectId: 'to-do-list-616ab',
    storageBucket: 'to-do-list-616ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABfHP8xwyTFdw-BQG6hnoHFVDu_hdDQ-A',
    appId: '1:384145309918:ios:efe624c26c98920d0b024f',
    messagingSenderId: '384145309918',
    projectId: 'to-do-list-616ab',
    storageBucket: 'to-do-list-616ab.appspot.com',
    iosClientId: '384145309918-rtgm6v97sj2fbtdkfcbvldrjpnnfspm4.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABfHP8xwyTFdw-BQG6hnoHFVDu_hdDQ-A',
    appId: '1:384145309918:ios:63c8564e824b664d0b024f',
    messagingSenderId: '384145309918',
    projectId: 'to-do-list-616ab',
    storageBucket: 'to-do-list-616ab.appspot.com',
    iosClientId: '384145309918-o03ei29t3mpohbjrj0s1g94micrl0g26.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoListApp.RunnerTests',
  );
}
